use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StandardColor {
    None,
    Black,
    White,
    Gray1,
    Gray2,
    Gray3,
    Gray4,
    Gray5,
    Gray6,
    Gray7,
    Gray8,
    Gray9,
    Red1,
    Red2,
    Red3,
    Red4,
    Red5,
    Red6,
    Red7,
    Red8,
    Red9,
    Orange1,
    Orange2,
    Orange3,
    Orange4,
    Orange5,
    Orange6,
    Orange7,
    Orange8,
    Orange9,
    Yellow1,
    Yellow2,
    Yellow3,
    Yellow4,
    Yellow5,
    Yellow6,
    Yellow7,
    Yellow8,
    Yellow9,
    Lime1,
    Lime2,
    Lime3,
    Lime4,
    Lime5,
    Lime6,
    Lime7,
    Lime8,
    Lime9,
    Green1,
    Green2,
    Green3,
    Green4,
    Green5,
    Green6,
    Green7,
    Green8,
    Green9,
    Emerald1,
    Emerald2,
    Emerald3,
    Emerald4,
    Emerald5,
    Emerald6,
    Emerald7,
    Emerald8,
    Emerald9,
    Cyan1,
    Cyan2,
    Cyan3,
    Cyan4,
    Cyan5,
    Cyan6,
    Cyan7,
    Cyan8,
    Cyan9,
    Blue1,
    Blue2,
    Blue3,
    Blue4,
    Blue5,
    Blue6,
    Blue7,
    Blue8,
    Blue9,
    Indigo1,
    Indigo2,
    Indigo3,
    Indigo4,
    Indigo5,
    Indigo6,
    Indigo7,
    Indigo8,
    Indigo9,
    Purple1,
    Purple2,
    Purple3,
    Purple4,
    Purple5,
    Purple6,
    Purple7,
    Purple8,
    Purple9,
    Magenta1,
    Magenta2,
    Magenta3,
    Magenta4,
    Magenta5,
    Magenta6,
    Magenta7,
    Magenta8,
    Magenta9,
    Crimson1,
    Crimson2,
    Crimson3,
    Crimson4,
    Crimson5,
    Crimson6,
    Crimson7,
    Crimson8,
    Crimson9,
}

impl StandardColor {
    pub fn value(&self) -> &'static str {
        match self {
            StandardColor::None => "none",
            StandardColor::Black => "#000000",
            StandardColor::White => "#FFFFFF",
            StandardColor::Gray1 => "#E6E6E6",
            StandardColor::Gray2 => "#CCCCCC",
            StandardColor::Gray3 => "#B3B3B3",
            StandardColor::Gray4 => "#999999",
            StandardColor::Gray5 => "#808080",
            StandardColor::Gray6 => "#666666",
            StandardColor::Gray7 => "#4D4D4D",
            StandardColor::Gray8 => "#333333",
            StandardColor::Gray9 => "#1A1A1A",
            StandardColor::Red1 => "#FFCCCC",
            StandardColor::Red2 => "#FF9999",
            StandardColor::Red3 => "#FF6666",
            StandardColor::Red4 => "#FF3333",
            StandardColor::Red5 => "#FF0000",
            StandardColor::Red6 => "#CC0000",
            StandardColor::Red7 => "#990000",
            StandardColor::Red8 => "#660000",
            StandardColor::Red9 => "#330000",
            StandardColor::Orange1 => "#FFE6CC",
            StandardColor::Orange2 => "#FFCC99",
            StandardColor::Orange3 => "#FFB366",
            StandardColor::Orange4 => "#FF9933",
            StandardColor::Orange5 => "#FF8000",
            StandardColor::Orange6 => "#CC6600",
            StandardColor::Orange7 => "#994C00",
            StandardColor::Orange8 => "#663300",
            StandardColor::Orange9 => "#331A00",
            StandardColor::Yellow1 => "#FFFFCC",
            StandardColor::Yellow2 => "#FFFF99",
            StandardColor::Yellow3 => "#FFFF66",
            StandardColor::Yellow4 => "#FFFF33",
            StandardColor::Yellow5 => "#FFFF00",
            StandardColor::Yellow6 => "#CCCC00",
            StandardColor::Yellow7 => "#999900",
            StandardColor::Yellow8 => "#666600",
            StandardColor::Yellow9 => "#333300",
            StandardColor::Lime1 => "#E6FFCC",
            StandardColor::Lime2 => "#CCFF99",
            StandardColor::Lime3 => "#B3FF66",
            StandardColor::Lime4 => "#99FF33",
            StandardColor::Lime5 => "#80FF00",
            StandardColor::Lime6 => "#66CC00",
            StandardColor::Lime7 => "#4D9900",
            StandardColor::Lime8 => "#336600",
            StandardColor::Lime9 => "#1A3300",
            StandardColor::Green1 => "#CCFFCC",
            StandardColor::Green2 => "#99FF99",
            StandardColor::Green3 => "#66FF66",
            StandardColor::Green4 => "#33FF33",
            StandardColor::Green5 => "#00FF00",
            StandardColor::Green6 => "#00CC00",
            StandardColor::Green7 => "#009900",
            StandardColor::Green8 => "#006600",
            StandardColor::Green9 => "#003300",
            StandardColor::Emerald1 => "#CCFFE6",
            StandardColor::Emerald2 => "#99FFCC",
            StandardColor::Emerald3 => "#66FFB3",
            StandardColor::Emerald4 => "#33FF99",
            StandardColor::Emerald5 => "#00FF80",
            StandardColor::Emerald6 => "#00CC66",
            StandardColor::Emerald7 => "#00994D",
            StandardColor::Emerald8 => "#006633",
            StandardColor::Emerald9 => "#00331A",
            StandardColor::Cyan1 => "#CCFFFF",
            StandardColor::Cyan2 => "#99FFFF",
            StandardColor::Cyan3 => "#66FFFF",
            StandardColor::Cyan4 => "#33FFFF",
            StandardColor::Cyan5 => "#00FFFF",
            StandardColor::Cyan6 => "#00CCCC",
            StandardColor::Cyan7 => "#009999",
            StandardColor::Cyan8 => "#006666",
            StandardColor::Cyan9 => "#003333",
            StandardColor::Blue1 => "#CCE5FF",
            StandardColor::Blue2 => "#99CCFF",
            StandardColor::Blue3 => "#66B2FF",
            StandardColor::Blue4 => "#3399FF",
            StandardColor::Blue5 => "#007FFF",
            StandardColor::Blue6 => "#0066CC",
            StandardColor::Blue7 => "#004C99",
            StandardColor::Blue8 => "#003366",
            StandardColor::Blue9 => "#001933",
            StandardColor::Indigo1 => "#CCCCFF",
            StandardColor::Indigo2 => "#9999FF",
            StandardColor::Indigo3 => "#6666FF",
            StandardColor::Indigo4 => "#3333FF",
            StandardColor::Indigo5 => "#0000FF",
            StandardColor::Indigo6 => "#0000CC",
            StandardColor::Indigo7 => "#000099",
            StandardColor::Indigo8 => "#000066",
            StandardColor::Indigo9 => "#000033",
            StandardColor::Purple1 => "#E5CCFF",
            StandardColor::Purple2 => "#CC99FF",
            StandardColor::Purple3 => "#B266FF",
            StandardColor::Purple4 => "#9933FF",
            StandardColor::Purple5 => "#7F00FF",
            StandardColor::Purple6 => "#6600CC",
            StandardColor::Purple7 => "#6600CC",
            StandardColor::Purple8 => "#330066",
            StandardColor::Purple9 => "#190033",
            StandardColor::Magenta1 => "#FFCCFF",
            StandardColor::Magenta2 => "#FF99CC",
            StandardColor::Magenta3 => "#FF66CC",
            StandardColor::Magenta4 => "#FF33FF",
            StandardColor::Magenta5 => "#FF00FF",
            StandardColor::Magenta6 => "#CC00CC",
            StandardColor::Magenta7 => "#990099",
            StandardColor::Magenta8 => "#660066",
            StandardColor::Magenta9 => "#330033",
            StandardColor::Crimson1 => "#FFCCE6",
            StandardColor::Crimson2 => "#FF99CC",
            StandardColor::Crimson3 => "#FF66B3",
            StandardColor::Crimson4 => "#FF3399",
            StandardColor::Crimson5 => "#FF0080",
            StandardColor::Crimson6 => "#CC0066",
            StandardColor::Crimson7 => "#99004D",
            StandardColor::Crimson8 => "#660033",
            StandardColor::Crimson9 => "#33001A",
        }
    }
}

impl fmt::Display for StandardColor {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.value())
    }
}
